version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - 8333:3000
    volumes:
      - /home/zach/.newsboat/urls:/config/urls
    environment:
      - NEWSBOAT_URL_FILE=/config/urls
